### This NoteBook provides some Notes about PyTorch Fundamental

In [1]:
import numpy as np
import torch
import torch.nn as nn
from torchvision import datasets

In [2]:
## check cuda
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [3]:
## from numpy to tensor and from tensor to numpy
a = np.array([[1,2,3,4],[5,6,7,8]])
b = torch.from_numpy(a)
print(b)
c = b.numpy()
print(c)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
## device and requires_grad parameters
my_device = ('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.ones(5, device=device, requires_grad=True)    
## requires_grad ----> calculate gradients for optimization
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

`Calculate the gradients with Autograd`

In [5]:
## Calculate gradients with Autograd
x = torch.randn(3, requires_grad=True)
print('x --> \n', x)

y = x + 2
print('y --> \n', y)

z = y * y * 2
z = z.mean()
print('z --> \n', z)

z.backward()  ## dz/dx

## get the graients
print('gradient --> \n', x.grad)

x --> 
 tensor([ 1.3509, -1.7170,  1.8842], requires_grad=True)
y --> 
 tensor([3.3509, 0.2830, 3.8842], grad_fn=<AddBackward0>)
z --> 
 tensor(17.5973, grad_fn=<MeanBackward0>)
gradient --> 
 tensor([4.4678, 0.3774, 5.1790])


In [6]:
x = torch.randint(low=0, high=7, size=(5,5), dtype=torch.float32, requires_grad=True)
print('x --> \n', x)

y = x**2 + 5
print('y --> \n', y)

z = y.mean()
print('z --> \n', z)

z.backward() ## dz/dx

## get the graients
print('gradient --> \n', x.grad)

x --> 
 tensor([[4., 2., 5., 3., 5.],
        [0., 3., 5., 3., 1.],
        [6., 4., 2., 6., 6.],
        [6., 6., 3., 1., 3.],
        [2., 3., 0., 1., 4.]], requires_grad=True)
y --> 
 tensor([[21.,  9., 30., 14., 30.],
        [ 5., 14., 30., 14.,  6.],
        [41., 21.,  9., 41., 41.],
        [41., 41., 14.,  6., 14.],
        [ 9., 14.,  5.,  6., 21.]], grad_fn=<AddBackward0>)
z --> 
 tensor(19.8800, grad_fn=<MeanBackward0>)
gradient --> 
 tensor([[0.3200, 0.1600, 0.4000, 0.2400, 0.4000],
        [0.0000, 0.2400, 0.4000, 0.2400, 0.0800],
        [0.4800, 0.3200, 0.1600, 0.4800, 0.4800],
        [0.4800, 0.4800, 0.2400, 0.0800, 0.2400],
        [0.1600, 0.2400, 0.0000, 0.0800, 0.3200]])


#### Done!